# Generated by Django 5.0.7 on 2024-08-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_conversion_rate_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='conversion_rate',
            field=models.FloatField(default=40),
        ),
    ]
