# Generated by Django 5.0.7 on 2024-08-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_conversion_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='conversion_rate',
        ),
    ]
